/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.xcompiler.analysis;

import br.com.ufs.xcompiler.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTBlank(TBlank node);
    void caseTInt(TInt node);
    void caseTReal(TReal node);
    void caseTBool(TBool node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTIf(TIf node);
    void caseTThen(TThen node);
    void caseTElse(TElse node);
    void caseTWhile(TWhile node);
    void caseTProcedure(TProcedure node);
    void caseTFunction(TFunction node);
    void caseTCons(TCons node);
    void caseTVar(TVar node);
    void caseTNum(TNum node);
    void caseTId(TId node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTVirgula(TVirgula node);
    void caseTIniParentese(TIniParentese node);
    void caseTFimParentese(TFimParentese node);
    void caseTIniChave(TIniChave node);
    void caseTFimChave(TFimChave node);
    void caseTIniColchete(TIniColchete node);
    void caseTFimColchete(TFimColchete node);
    void caseTSoma(TSoma node);
    void caseTSubtr(TSubtr node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTEqual(TEqual node);
    void caseTMenor(TMenor node);
    void caseTNot(TNot node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTAtrib(TAtrib node);
    void caseTPipe(TPipe node);
    void caseTComentLinha(TComentLinha node);
    void caseTComentBloco(TComentBloco node);
    void caseTFimComentBloco(TFimComentBloco node);
    void caseTCorpoComentBloco(TCorpoComentBloco node);
    void caseTStar(TStar node);
    void caseTSlash(TSlash node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
